seed: 42
total_timesteps: 400000
learning_rate: 0.0001
n_steps: 2048
batch_size: 512
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.15
ent_coef: 0.006
vf_coef: 0.5
max_grad_norm: 0.5
n_epochs: 8
device: "auto"
checkpoint_dir: "outputs/checkpoints_20r_10n"
tensorboard_log: "outputs/tensorboard_scoring_20r_10n"
best_model_dir: "outputs/best_model_scoring_20r_10n"
eval_log_path: "outputs/eval_scoring_20r_10n"
eval_freq: 10000
n_eval_episodes: 8
model_name: "ppo_gat_scoring_20r_10n"
